inherits = "term16_light"

"ui.background.separator" = { bg = "#bdc2ff" }
"ui.cursor" = { fg = "FFFFFF", bg = "#FFFFFF" }
"ui.cursor.match" = { fg = "#000000", bg = "#FFFFFF" }
"ui.cursor.primary" = { fg = "#000000", bg = "#FFFFFF" }
"ui.cursor.secondary" = { fg = "#000000", bg = "#FFFFFF" }

"ui.cursorline.primary" = { bg = "#444559" }
"ui.cursorline.secondary" = { bg = "#444559" }

"ui.cursorcolumn.primary" = { bg = "#444559" }
"ui.cursorcolumn.secondary" = { bg = "#444559" }

"ui.gutter" = { fg = "#c4c4dd" }
"ui.gutter.selected" = { bg = "none" }

"ui.linenr" = { fg = "#c4c4dd" }
# "ui.linenr.selected" = { fg = "#dfe0ff", modifiers = ["bold"] }
"ui.linenr.selected" = { fg = "F8F8F8", modifiers = ["bold"] }

"ui.menu" = { fg = "F8F8F8"}
"ui.menu.selected" = { fg = "#252b61", bg = "#bdc2ff", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "#c4c4dd" }

"ui.help" = { fg = "#bdc2ff" }
"ui.text" = { fg = "#bdc2ff" }
"ui.text.focus" = { fg = "#e1e0f9" }

"ui.selection" = { bg = "#444559" }
"ui.popup" = { fg = "#000000", bg = "none" }
"ui.statusline" = { bg = "#3c4279" }
"ui.statusline.inactive" = { fg = "#e1e0f9", modifiers = ["underlined"] }
"ui.statusline.insert" = { fg = "#252b61", bg = "#bdc2ff" }
"ui.statusline.select" = { fg = "#2d2f42", bg = "#c4c4dd" }

"ui.virtual" = { fg = "#c4c4dd" }
"ui.virtual.indent-guide" = { fg = "#e7b9d6", modifiers = ["dim"] }
"ui.virtual.ruler" = { bg = "#444559" }
"ui.virtual.wrap" = { fg = "#c4c4dd" }

"ui.window" = { fg = "#bdc2ff", modifiers = ["bold"] }

# Syntax (High visibility for warm theme)

"comment" = { fg = "#F8F8F8", modifiers = ["bold"] }

"attribute" = "#bdc2ff"
"constant" = { fg = "#bdc2ff", modifiers = ["bold"] }
"constant.numeric" = { fg = "#c4c4dd", modifiers = ["bold"] }
"constant.character.escape" = "#444559"

"constructor" = "#bdc2ff"
"function" = "#bdc2ff"
"function.builtin" = { fg = "#c4c4dd", modifiers = ["bold"] }

"tag" = { fg = "#444559", modifiers = ["bold"] }
"type" = "#e7b9d6"
"type.builtin" = { fg = "#e1e0f9", modifiers = ["bold"] }
"type.enum.variant" = { fg = "#e7b9d6", modifiers = ["bold"] }

"string" = "#e1e0f9"
"special" = "#ffb4ab"

"variable" = { fg = "#bdc2ff" }
"variable.parameter" = { fg = "#dfe0ff", modifiers = ["italic"] }
"variable.other.member" = "#c4c4dd"

"keyword" = { fg = "#bdc2ff", modifiers = ["bold"] }
"keyword.control.exception" = { fg = "#690005" }
"keyword.directive" = { fg = "#bdc2ff", modifiers = ["bold"] }
"keyword.operator" = { fg = "#c4c4dd", modifiers = ["bold"] }

"label" = "#690005"
"namespace" = { fg = "#444559", modifiers = ["bold"] }

"markup.heading" = { fg = "#bdc2ff", modifiers = ["bold"] }
"markup.list" = "#690005"
"markup.bold" = { fg = "#bdc2ff", modifiers = ["bold"] }
"markup.italic" = { fg = "#444559", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "#5e3c53", modifiers = ["italic"] }
"markup.link.text" = { fg = "#c4c4dd", modifiers = ["bold"] }
"markup.quote" = "#bdc2ff"
"markup.raw" = "#3c4279"

"diff.plus" = "#c4c4dd"
"diff.delta" = "#bdc2ff"
"diff.minus" = "#ffb4ab"

"diagnostic.hint" = { underline = { color = "#bdc2ff", style = "curl" } }
"diagnostic.info" = { underline = { color = "#c4c4dd", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#e7b9d6", style = "curl" } }
"diagnostic.error" = { underline = { color = "#ffb4ab", style = "curl" } }

"hint" = "#3c4279"
"info" = "#bdc2ff"
"debug" = "#c4c4dd"
"warning" = "#e7b9d6"
"error" = "#ffb4ab"
