music_directory      "/home/ravish/music"
playlist_directory   "/home/ravish/.config/mpd/playlists"
db_file              "/home/ravish/.config/mpd/database"
log_file             "/home/ravish/.config/mpd/log"

# Changed from /run/ to your home folder to avoid permission errors
pid_file             "/home/ravish/.config/mpd/pid"

state_file           "/home/ravish/.config/mpd/state"
sticker_file         "/home/ravish/.config/mpd/sticker.sql"

# Commented out so MPD runs as your user "ravish"
# user "mpd"

bind_to_address      "127.0.0.1"
port                 "6600"

restore_paused       "yes"
metadata_to_use      "artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update          "yes"
follow_outside_symlinks "yes"

audio_output {
        type            "pipewire"
        name            "PipeWire output"
        # Optional
        #target          "bluez_output.F4_9D_8A_B4_8D_37.1"
}

audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
