# Shell variables
# Generated by 'wal'
wallpaper="{{image}}"

# Special
background='{{colors.surface.default.hex}}'
foreground='{{colors.primary.default.hex}}'
cursor='{{colors.surface.default.hex}}'

# Colors
    color0='{{colors.surface_container_lowest.default.hex}}'
    color1='{{colors.primary.default.hex}}'
    color2='{{colors.primary_fixed_dim.default.hex}}'
    color3='{{colors.background.default.hex}}'
    color4='{{colors.surface.default.hex}}'
    color5='{{colors.on_primary_container.default.hex}}'
    color6='{{colors.outline_variant.default.hex}}'
    color7='{{colors.primary.default.hex}}'
    color8='{{colors.on_primary_container.default.hex}}'
    color9='{{colors.background.default.hex}}'
    color10='{{colors.on_secondary_container.default.hex}}'
    color11='{{colors.background.default.hex}}'
    color12='{{colors.source_color.default.hex}}'
    color13='{{colors.surface_bright.default.hex}}'
    color14='{{colors.primary.default.hex}}'
    color15='{{colors.on_surface.default.hex}}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
