theme = "helix"

[editor]
color-modes = true
mouse = true
bufferline = "multiple"
middle-click-paste = true
auto-completion = true
completion-replace = true
path-completion = true
auto-format = false
undercurl = true
auto-info = true
indent-heuristic = "tree-sitter"
end-of-line-diagnostics = "hint"
popup-border = "all"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "position", "separator", "total-line-numbers", "separator", "file-type"]
separator = ""
mode.normal = "🟤 NORMAL"
mode.insert = "🟠 INSERT"
mode.select = "🔴 SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true

[editor.lsp]
enable = true
display-inlay-hints = true
display-messages = true
auto-signature-help = true
snippets = true
display-signature-help-docs = true

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_above", "extend_to_line_bounds"]
G = "goto_last_line"
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
d = "delete_selection_noyank"
c = "change_selection_noyank"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[keys.insert]
C-j = "move_char_left"
C-l = "move_char_right"

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
