use-grammars = { only = ["bash", "c", "sway", "xml"] }

[[language]]
name = "c"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "xml"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "sway"
file-types = [ { glob = "/home/ravish/.config/sway/config" } ]
grammar = "sway"
comment-token = "#"

[language-server]
c = { command = "clangd", args = ["--completion-style=detailed", "--header-insertion=never"] }
